name: native_http
description: A package that calls network from native platform ie OkHttp on Android and URLSession iOS.
version: 1.0.1+2
homepage: https://github.com/awazgyawali/native_http

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
      platforms:
        android:
          package: com.brainants.nativehttp.native_http
          pluginClass: NativeHttpPlugin
        ios:
          pluginClass: NativeHttpPlugin
